### ISSUE TITLE
fetch categories from fake store api

### ISSUE THREAD

**Issue by jihtat** [jihtat/store#2]

**Comment by fatihaad** [comment]
import { Navbar } from './components/Navbar';
import { Footer } from './components/Footer';
import React, {useState, useEffect} from 'react';
import './App.css';

function App() {
  let [getCategory, useCategory] = useState(null)
  useEffect (() => {
    fetch('https://fakestoreapi.com/products/categories')
    .then(response => response.json())
    .then(data => useCategory(data.message))
  },[])

 
  return (
    <div>
     <Navbar/>
     <Footer/>
     
    </div>
  );
}
export default App;
